import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { Keypair } from "@solana/web3.js";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { requireAdmin } from "@/lib/auth/middleware";
import { checkSameOrigin } from "@/lib/auth/csrf";
import { purgeStale } from "@/lib/jobs/purge-stale";
import { banAndBlockAi, isPubkeyBanned } from "@/lib/ban";
import { ensureTestAiUser, signTestAiRequest } from "@/lib/test-ai";
import type { Category } from "@prisma/client";

const schema = z.discriminatedUnion("scenario", [
  z.object({ scenario: z.literal("deadline-expiry-refund") }),
  z.object({ scenario: z.literal("cancel-task") }),
  z.object({ scenario: z.literal("moderation-ban") }),
]);

type Step = { name: string; ok: boolean; data?: unknown; error?: string };

async function createTestTask(opts: {
  posterId: string;
  status?: "OPEN" | "PENDING_DEPOSIT";
  slotCount?: number;
  deadlineAt?: Date | null;
  titleSuffix?: string;
}) {
  const now = new Date();
  return prisma.task.create({
    data: {
      posterId: opts.posterId,
      type: "MICRO",
      title: `[scenario] ${opts.titleSuffix ?? "test task"}`,
      description: "Auto-generated by the admin scenario runner.",
      category: "PHOTO_VERIFICATION" satisfies Category,
      urgency: "NORMAL",
      privacy: "PUBLIC",
      slotCount: opts.slotCount ?? 1,
      estimatedMinutes: 15,
      statedPriceUsdt: new Prisma.Decimal("5"),
      instantAcceptUsdt: new Prisma.Decimal("3"),
      totalUsdt: new Prisma.Decimal((5 * (opts.slotCount ?? 1) * 1.05).toFixed(6)),
      status: opts.status ?? "OPEN",
      escrowTxSig: (opts.status ?? "OPEN") === "OPEN" ? `scenario-${Date.now()}` : null,
      fundedAt: (opts.status ?? "OPEN") === "OPEN" ? now : null,
      deadlineAt: opts.deadlineAt ?? null,
      expiresAt: new Date(now.getTime() + 30 * 24 * 3_600_000),
      biddingHours: 24,
      biddingClosesAt:
        (opts.status ?? "OPEN") === "OPEN"
          ? new Date(now.getTime() + 24 * 3_600_000)
          : null,
      slots: { create: Array.from({ length: opts.slotCount ?? 1 }, () => ({ status: "OPEN" as const })) },
    },
    select: { id: true, status: true },
  });
}

export async function POST(req: NextRequest) {
  const csrf = checkSameOrigin(req);
  if (csrf) return csrf;
  const auth = await requireAdmin();
  if (auth instanceof NextResponse) return auth;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid_json" }, { status: 400 });
  }
  const parsed = schema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "invalid_payload" }, { status: 400 });
  }

  const transcript: Step[] = [];
  const step = async <T>(name: string, fn: () => Promise<T>): Promise<T | null> => {
    try {
      const data = await fn();
      transcript.push({ name, ok: true, data });
      return data;
    } catch (err) {
      transcript.push({
        name,
        ok: false,
        error: err instanceof Error ? err.message : String(err),
      });
      return null;
    }
  };

  if (parsed.data.scenario === "deadline-expiry-refund") {
    const testAi = await ensureTestAiUser();
    const task = await step("create OPEN task with 2 slots", () =>
      createTestTask({ posterId: testAi.id, slotCount: 2, titleSuffix: "deadline-expiry" }),
    );
    if (!task) return NextResponse.json({ ok: false, transcript });

    await step("back-date deadline to 1m ago", async () => {
      const at = new Date(Date.now() - 60_000);
      await prisma.task.update({ where: { id: task.id }, data: { deadlineAt: at } });
      return { deadlineAt: at.getTime() };
    });

    const processed = await step("run purgeStale()", () => purgeStale());

    const after = await step("read task + slots after sweep", async () => {
      const row = await prisma.task.findUnique({
        where: { id: task.id },
        select: {
          id: true,
          status: true,
          slots: { select: { id: true, status: true, decidedAt: true } },
        },
      });
      if (!row) return null;
      return {
        ...row,
        slots: row.slots.map((s) => ({
          ...s,
          // Unix ms on the wire (admin transcript output).
          decidedAt: s.decidedAt ? s.decidedAt.getTime() : null,
        })),
      };
    });

    return NextResponse.json({
      ok: transcript.every((s) => s.ok),
      taskId: task.id,
      processed,
      after,
      transcript,
    });
  }

  if (parsed.data.scenario === "cancel-task") {
    const testAi = await ensureTestAiUser();
    const task = await step("create OPEN task", () =>
      createTestTask({ posterId: testAi.id, slotCount: 1, titleSuffix: "cancel" }),
    );
    if (!task) return NextResponse.json({ ok: false, transcript });

    const cancelPath = `/api/v1/tasks/${task.id}/cancel`;
    const rawBody = "";
    const cancelResp = await step("signed AI POST /cancel", async () => {
      const headers = {
        "content-type": "application/json",
        ...signTestAiRequest({ method: "POST", path: cancelPath, rawBody }),
      };
      const res = await fetch(new URL(cancelPath, req.nextUrl.origin), {
        method: "POST",
        headers,
        body: rawBody,
      });
      const data = await res.json().catch(() => null);
      return { upstreamStatus: res.status, data };
    });

    const after = await step("read task after cancel", () =>
      prisma.task.findUnique({
        where: { id: task.id },
        select: {
          id: true,
          status: true,
          slots: { select: { id: true, status: true } },
        },
      }),
    );

    return NextResponse.json({
      ok: transcript.every((s) => s.ok),
      taskId: task.id,
      cancelResp,
      after,
      transcript,
    });
  }

  if (parsed.data.scenario === "moderation-ban") {
    // Use a throwaway AI keypair so we never ban the configured test_ai.
    const kp = Keypair.generate();
    const pubkey = kp.publicKey.toBase58();
    const username = `burn_${Date.now().toString(36).slice(-6)}`;

    const burnUser = await step("create throwaway AI user", () =>
      prisma.user.create({
        data: {
          username,
          solanaPubkey: pubkey,
          role: "AI",
          txVerified: true,
          tosAcceptedAt: new Date(),
          tosVersion: process.env.TOS_VERSION || "test",
        },
        select: { id: true, username: true, solanaPubkey: true },
      }),
    );
    if (!burnUser) return NextResponse.json({ ok: false, transcript });

    await step("banAndBlockAi(...)", () =>
      banAndBlockAi(burnUser.id, {
        reason: "prohibited_content",
        category: "test_injection",
        detail: "admin scenario runner",
      }),
    );

    const bannedCheck = await step("isPubkeyBanned(pubkey)", () => isPubkeyBanned(pubkey));

    const afterUser = await step("re-read user (banned/suspended flags)", () =>
      prisma.user.findUnique({
        where: { id: burnUser.id },
        select: { id: true, username: true, banned: true, suspended: true },
      }),
    );

    const blocklist = await step("BannedIdentity rows for this pubkey/username", async () =>
      prisma.bannedIdentity.findMany({
        where: { OR: [{ pubkey }, { username }] },
        select: { id: true, pubkey: true, username: true, category: true, detail: true, bannedAt: true },
      }),
    );

    return NextResponse.json({
      ok: transcript.every((s) => s.ok),
      burned: { id: burnUser.id, username, pubkey },
      bannedCheck,
      afterUser,
      blocklist,
      transcript,
    });
  }

  return NextResponse.json({ error: "unhandled_scenario" }, { status: 400 });
}
