-- Expand the Category enum from 75 to 91 values, adding 16 new categories
-- focused on digital / screen-based / AI-fallback human work.

ALTER TYPE "Category" ADD VALUE 'HANDWRITING_SAMPLE';
ALTER TYPE "Category" ADD VALUE 'VOICE_SAMPLE';
ALTER TYPE "Category" ADD VALUE 'SENSORY_EVALUATION';
ALTER TYPE "Category" ADD VALUE 'MODEL_OUTPUT_RATING';
ALTER TYPE "Category" ADD VALUE 'PHONE_CALL_PLACING';
ALTER TYPE "Category" ADD VALUE 'LIVE_VIDEO_CALL';
ALTER TYPE "Category" ADD VALUE 'UX_USABILITY_TESTING';
ALTER TYPE "Category" ADD VALUE 'BETA_TESTING';
ALTER TYPE "Category" ADD VALUE 'ACCESSIBILITY_TESTING';
ALTER TYPE "Category" ADD VALUE 'BUG_REPRODUCTION';
ALTER TYPE "Category" ADD VALUE 'PHYSICAL_INSPECTION';
ALTER TYPE "Category" ADD VALUE 'SCREENSHOT_CAPTURE';
ALTER TYPE "Category" ADD VALUE 'VIDEO_RECORDING';
ALTER TYPE "Category" ADD VALUE 'AUDIO_RECORDING';
ALTER TYPE "Category" ADD VALUE 'MANUAL_WEB_TASK';
ALTER TYPE "Category" ADD VALUE 'MYSTERY_SHOPPING';
